version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      # - $(aws ecr get-login --no-include-email --region  ap-southeast-1)
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 024434444420.dkr.ecr.ap-southeast-1.amazonaws.com
      - REPOSITORY_URI=024434444420.dkr.ecr.ap-southeast-1.amazonaws.com/deploy_ecs
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=latest
  build:
    commands:
      - echo Building an image
      - docker build -t deploy_ecs .
      - docker tag deploy_ecs:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Pushing an image
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image details
      - printf '[{"name":"demo_ecs", "imageUri":"%s"}]'
        deploy_ecs:latest > imagedDetail.json
      - cat imagedDetail.json

artifacts:
  files:
    - imagedDetail.json
